/**
 * Generates OpenAPI metadata for runtime spec building
 *
 * Instead of generating a massive static JSON spec, this generates
 * compact model metadata that can build the spec dynamically at runtime.
 */
import { FieldDefinition, ModelDefinition, RelationshipDefinition } from '../types/model.types.ts';
import { normalizeAccept, normalizeExpose } from '../utils/field.utils.ts';

/**
 * Generates OpenAPI metadata file for runtime spec building
 */
export class OpenAPIMetadataGenerator {
  private models: ModelDefinition[];

  constructor(models: ModelDefinition[]) {
    this.models = models;
  }

  /**
   * Generate the metadata file content
   */
  generate(): string {
    const modelsMeta = this.models.map((model) => this.generateModelMeta(model));

    return `/**
 * OpenAPI Model Metadata
 *
 * Compact metadata for building OpenAPI spec at runtime.
 * Generated by COG - Do not modify manually
 */

// ============================================
// Type Definitions
// ============================================

export interface FieldMeta {
  name: string;
  type: string;
  format?: string;
  description?: string;
  required: boolean;
  nullable: boolean;
  array: boolean;
  enum?: string[];
  maxLength?: number;
  /** Include in response schema */
  exposeRead: boolean;
  /** Include in create input schema */
  acceptCreate: boolean;
  /** Include in update input schema */
  acceptUpdate: boolean;
  /** Has auto-generated default (skip in create schema) */
  hasDefault: boolean;
}

export interface RelationshipMeta {
  name: string;
  type: 'oneToMany' | 'manyToOne' | 'manyToMany' | 'oneToOne';
  target: string;
  through?: string;
}

export interface EndpointConfig {
  create: boolean;
  readOne: boolean;
  readMany: boolean;
  update: boolean;
  delete: boolean;
}

export interface ModelMeta {
  name: string;
  nameLower: string;
  description?: string;
  fields: FieldMeta[];
  relationships: RelationshipMeta[];
  endpoints: EndpointConfig;
  hasTimestamps: boolean;
}

// ============================================
// Model Metadata
// ============================================

export const modelMetadata: ModelMeta[] = ${JSON.stringify(modelsMeta, null, 2)};

// ============================================
// Lookup Helpers
// ============================================

export const getModelMeta = (name: string): ModelMeta | undefined =>
  modelMetadata.find((m) => m.name === name || m.nameLower === name.toLowerCase());

export const getModelNames = (): string[] =>
  modelMetadata.map((m) => m.name);
`;
  }

  /**
   * Generate metadata for a single model
   */
  private generateModelMeta(model: ModelDefinition): Record<string, unknown> {
    return {
      name: model.name,
      nameLower: model.name.toLowerCase(),
      description: model.description,
      fields: model.fields.map((field) => this.generateFieldMeta(field, model)),
      relationships: (model.relationships || []).map((rel) => this.generateRelationshipMeta(rel)),
      endpoints: {
        create: model.endpoints?.create !== false,
        readOne: model.endpoints?.readOne !== false,
        readMany: model.endpoints?.readMany !== false,
        update: model.endpoints?.update !== false,
        delete: model.endpoints?.delete !== false,
      },
      hasTimestamps: model.timestamps === true,
    };
  }

  /**
   * Generate metadata for a single field
   */
  private generateFieldMeta(field: FieldDefinition, model: ModelDefinition): Record<string, unknown> {
    const exposeConfig = normalizeExpose(field.expose);
    const acceptConfig = normalizeAccept(field.accept);
    const typeInfo = this.getOpenAPIType(field, model);

    const meta: Record<string, unknown> = {
      name: field.name,
      type: typeInfo.type,
      required: field.required === true || field.primaryKey === true,
      nullable: !field.required && !field.primaryKey,
      array: field.array === true,
      exposeRead: exposeConfig.read,
      acceptCreate: acceptConfig.create,
      acceptUpdate: acceptConfig.update,
      hasDefault: field.primaryKey === true && field.defaultValue !== undefined,
    };

    if (typeInfo.format) {
      meta.format = typeInfo.format;
    }

    if (field.description) {
      meta.description = field.description;
    } else if (field.type === 'date') {
      meta.description = 'EPOCH milliseconds';
    }

    if (typeInfo.enum) {
      meta.enum = typeInfo.enum;
    }

    if (field.maxLength) {
      meta.maxLength = field.maxLength;
    }

    return meta;
  }

  /**
   * Generate metadata for a relationship
   */
  private generateRelationshipMeta(rel: RelationshipDefinition): Record<string, unknown> {
    const meta: Record<string, unknown> = {
      name: rel.name,
      type: rel.type,
      target: rel.target,
    };

    if (rel.through) {
      meta.through = rel.through;
    }

    return meta;
  }

  /**
   * Get OpenAPI type information for a field
   */
  private getOpenAPIType(
    field: FieldDefinition,
    model: ModelDefinition,
  ): { type: string; format?: string; enum?: string[] } {
    // Handle enum fields
    if (field.type === 'enum') {
      let enumValues: string[] = [];
      let isBitwise = false;

      if (field.enumName && model.enums) {
        const enumDef = model.enums.find((e) => e.name === field.enumName);
        if (enumDef) {
          enumValues = enumDef.values;
          isBitwise = enumDef.useBitwise === true;
        }
      } else if (field.enumValues) {
        enumValues = field.enumValues;
      }

      if (isBitwise) {
        return { type: 'integer', format: 'int32' };
      }

      return { type: 'string', enum: enumValues };
    }

    const typeMap: Record<string, { type: string; format?: string }> = {
      'text': { type: 'string' },
      'string': { type: 'string' },
      'integer': { type: 'integer', format: 'int32' },
      'bigint': { type: 'integer', format: 'int64' },
      'decimal': { type: 'number', format: 'double' },
      'boolean': { type: 'boolean' },
      'date': { type: 'integer', format: 'int64' },
      'uuid': { type: 'string', format: 'uuid' },
      'json': { type: 'object' },
      'jsonb': { type: 'object' },
      // PostGIS types
      'point': { type: 'object' },
      'linestring': { type: 'object' },
      'polygon': { type: 'object' },
      'multipoint': { type: 'object' },
      'multilinestring': { type: 'object' },
      'multipolygon': { type: 'object' },
      'geometry': { type: 'object' },
      'geography': { type: 'object' },
    };

    return typeMap[field.type] || { type: 'string' };
  }
}
