/**
 * Generates the dynamic OpenAPI spec builder
 *
 * This generates a runtime builder that constructs the OpenAPI spec
 * from compact model metadata instead of embedding a massive static JSON.
 */
export class OpenAPIBuilderGenerator {
  /**
   * Generate the OpenAPI builder file content
   */
  generate(): string {
    return `/**
 * Dynamic OpenAPI 3.1.0 Specification Builder
 *
 * Builds OpenAPI spec at runtime from model metadata.
 * Generated by COG - Do not modify manually
 */

import type { OpenAPIV3_1 as OpenAPI } from 'openapi-types';
import { DomainException } from '../domain/exceptions.ts';
import { modelMetadata, type ModelMeta, type FieldMeta, type RelationshipMeta } from './openapi-metadata.ts';

// ============================================
// Main Builder Functions
// ============================================

/**
 * Build OpenAPI specification with the given basePath
 */
export const buildOpenAPISpec = (basePath: string): OpenAPI.Document => {
  if (!basePath) {
    throw new DomainException('basePath is required to build OpenAPI specification');
  }

  const spec: OpenAPI.Document = {
    openapi: '3.1.0',
    info: {
      title: 'Generated CRUD API',
      version: '1.0.0',
      description: 'Auto-generated REST API for CRUD operations.',
    },
    servers: [{ url: basePath, description: 'API base path' }],
    paths: {},
    components: {
      schemas: buildCommonSchemas(),
      parameters: buildCommonParameters(),
      responses: buildCommonResponses(),
    },
    tags: [],
  };

  // Build paths and schemas for each model
  for (const model of modelMetadata) {
    // Add tag
    (spec.tags as OpenAPI.TagObject[]).push({
      name: model.name,
      description: model.description || \`\${model.name} operations\`,
    });

    // Add schemas
    spec.components!.schemas![model.name] = buildModelSchema(model, 'response');
    spec.components!.schemas![\`\${model.name}Create\`] = buildModelSchema(model, 'create');
    spec.components!.schemas![\`\${model.name}Update\`] = buildModelSchema(model, 'update');

    // Add CRUD paths
    const listPath = buildListAndCreatePaths(model);
    if (Object.keys(listPath).length > 0) {
      spec.paths![\`/\${model.nameLower}\`] = listPath;
    }

    const detailPath = buildDetailPaths(model);
    if (Object.keys(detailPath).length > 0) {
      spec.paths![\`/\${model.nameLower}/{id}\`] = detailPath;
    }

    // Add relationship paths
    for (const rel of model.relationships) {
      if (rel.type === 'oneToMany') {
        spec.paths![\`/\${model.nameLower}/{id}/\${rel.target.toLowerCase()}List\`] =
          buildOneToManyPath(model, rel);
      } else if (rel.type === 'manyToMany') {
        const targetLower = rel.target.toLowerCase();
        spec.paths![\`/\${model.nameLower}/{id}/\${targetLower}List\`] =
          buildManyToManyListPaths(model, rel);
        spec.paths![\`/\${model.nameLower}/{id}/\${targetLower}List/{\${targetLower}Id}\`] =
          buildManyToManyDetailPaths(model, rel);
      }
    }
  }

  return spec;
};

/**
 * Merge custom OpenAPI specification with generated spec
 */
export const mergeOpenAPISpec = (
  basePath: string,
  customSpec: Partial<OpenAPI.Document>,
): OpenAPI.Document => {
  const generatedSpec = buildOpenAPISpec(basePath);

  return {
    ...generatedSpec,
    info: { ...generatedSpec.info, ...customSpec.info },
    servers: [...(generatedSpec.servers || []), ...(customSpec.servers || [])],
    paths: { ...generatedSpec.paths, ...customSpec.paths },
    components: {
      schemas: { ...generatedSpec.components?.schemas, ...customSpec.components?.schemas },
      responses: { ...generatedSpec.components?.responses, ...customSpec.components?.responses },
      parameters: { ...generatedSpec.components?.parameters, ...customSpec.components?.parameters },
      requestBodies: { ...generatedSpec.components?.requestBodies, ...customSpec.components?.requestBodies },
      securitySchemes: { ...generatedSpec.components?.securitySchemes, ...customSpec.components?.securitySchemes },
    },
    tags: [...(generatedSpec.tags || []), ...(customSpec.tags || [])],
    security: customSpec.security || generatedSpec.security,
  };
};

/**
 * Get OpenAPI specification as JSON string
 */
export const getOpenAPIJSON = (
  basePath: string,
  customSpec?: Partial<OpenAPI.Document>,
): string => {
  const spec = customSpec ? mergeOpenAPISpec(basePath, customSpec) : buildOpenAPISpec(basePath);
  return JSON.stringify(spec, null, 2);
};

// ============================================
// Schema Builders
// ============================================

const buildModelSchema = (
  model: ModelMeta,
  schemaType: 'response' | 'create' | 'update',
): OpenAPI.SchemaObject => {
  const schema: OpenAPI.SchemaObject = {
    type: 'object',
    properties: {},
    required: [],
  };

  if (model.description) {
    schema.description = model.description;
  }

  for (const field of model.fields) {
    // Determine inclusion based on schema type
    let include = false;
    if (schemaType === 'response') {
      include = field.exposeRead;
    } else if (schemaType === 'create') {
      include = field.acceptCreate && !field.hasDefault;
    } else {
      include = field.acceptUpdate;
    }

    if (!include) continue;

    schema.properties![field.name] = buildFieldSchema(field);

    // Add to required (not for update schemas)
    if (schemaType !== 'update' && field.required && !field.hasDefault) {
      (schema.required as string[]).push(field.name);
    }
  }

  // Add timestamps for response schema
  if (schemaType === 'response' && model.hasTimestamps) {
    schema.properties!.createdAt = {
      type: 'integer',
      format: 'int64',
      description: 'Creation timestamp (EPOCH milliseconds)',
    };
    schema.properties!.updatedAt = {
      type: 'integer',
      format: 'int64',
      description: 'Last update timestamp (EPOCH milliseconds)',
    };
    (schema.required as string[]).push('createdAt', 'updatedAt');
  }

  // Clean up empty required array
  if ((schema.required as string[]).length === 0) {
    delete schema.required;
  }

  return schema;
};

const buildFieldSchema = (field: FieldMeta): OpenAPI.SchemaObject => {
  const schema: OpenAPI.SchemaObject = { type: field.type as OpenAPI.NonArraySchemaObjectType };

  if (field.format) {
    schema.format = field.format;
  }

  if (field.description) {
    schema.description = field.description;
  }

  if (field.enum) {
    schema.enum = field.enum;
  }

  if (field.maxLength) {
    schema.maxLength = field.maxLength;
  }

  // Handle arrays
  if (field.array) {
    return {
      type: 'array',
      items: schema,
      description: \`Array of \${field.description || field.type}\`,
    };
  }

  // Handle nullable (OpenAPI 3.1.0 style)
  if (field.nullable) {
    schema.type = [field.type, 'null'] as unknown as OpenAPI.NonArraySchemaObjectType;
  }

  return schema;
};

// ============================================
// Path Builders
// ============================================

const buildListAndCreatePaths = (model: ModelMeta): OpenAPI.PathItemObject => {
  const paths: OpenAPI.PathItemObject = {};

  if (model.endpoints.readMany) {
    paths.get = {
      tags: [model.name],
      summary: \`List \${model.name} records\`,
      description: \`Retrieve a paginated list of \${model.name} records\`,
      operationId: \`list\${model.name}\`,
      parameters: [
        { $ref: '#/components/parameters/LimitParameter' },
        { $ref: '#/components/parameters/OffsetParameter' },
        { $ref: '#/components/parameters/OrderByParameter' },
        { $ref: '#/components/parameters/OrderDirectionParameter' },
        { $ref: '#/components/parameters/WhereParameter' },
      ],
      responses: {
        '200': {
          description: 'Successful response',
          content: {
            'application/json': {
              schema: {
                type: 'object',
                properties: {
                  data: { type: 'array', items: { $ref: \`#/components/schemas/\${model.name}\` } },
                  pagination: {
                    type: 'object',
                    properties: {
                      total: { type: 'integer' },
                      limit: { type: 'integer' },
                      offset: { type: 'integer' },
                    },
                  },
                },
              },
            },
          },
        },
        '500': { $ref: '#/components/responses/ServerError' },
      },
    };
  }

  if (model.endpoints.create) {
    paths.post = {
      tags: [model.name],
      summary: \`Create a \${model.name}\`,
      description: \`Create a new \${model.name}\`,
      operationId: \`create\${model.name}\`,
      requestBody: {
        required: true,
        content: {
          'application/json': {
            schema: { $ref: \`#/components/schemas/\${model.name}Create\` },
          },
        },
      },
      responses: {
        '201': {
          description: 'Created successfully',
          content: {
            'application/json': {
              schema: { $ref: \`#/components/schemas/\${model.name}\` },
            },
          },
        },
        '400': { $ref: '#/components/responses/ValidationError' },
        '500': { $ref: '#/components/responses/ServerError' },
      },
    };
  }

  return paths;
};

const buildDetailPaths = (model: ModelMeta): OpenAPI.PathItemObject => {
  const paths: OpenAPI.PathItemObject = {};

  if (model.endpoints.readOne) {
    paths.get = {
      tags: [model.name],
      summary: \`Get \${model.name} by ID\`,
      description: \`Retrieve a single \${model.name} by its ID\`,
      operationId: \`get\${model.name}ById\`,
      parameters: [
        { $ref: '#/components/parameters/IdParameter' },
        {
          name: 'include',
          in: 'query',
          description: 'Comma-separated list of relationships to include',
          schema: { type: 'string' },
        },
      ],
      responses: {
        '200': {
          description: 'Successful response',
          content: {
            'application/json': {
              schema: { $ref: \`#/components/schemas/\${model.name}\` },
            },
          },
        },
        '404': { $ref: '#/components/responses/NotFound' },
        '500': { $ref: '#/components/responses/ServerError' },
      },
    };
  }

  if (model.endpoints.update) {
    paths.put = {
      tags: [model.name],
      summary: \`Update \${model.name}\`,
      description: \`Update an existing \${model.name}\`,
      operationId: \`update\${model.name}\`,
      parameters: [{ $ref: '#/components/parameters/IdParameter' }],
      requestBody: {
        required: true,
        content: {
          'application/json': {
            schema: { $ref: \`#/components/schemas/\${model.name}Update\` },
          },
        },
      },
      responses: {
        '200': {
          description: 'Updated successfully',
          content: {
            'application/json': {
              schema: { $ref: \`#/components/schemas/\${model.name}\` },
            },
          },
        },
        '400': { $ref: '#/components/responses/ValidationError' },
        '404': { $ref: '#/components/responses/NotFound' },
        '500': { $ref: '#/components/responses/ServerError' },
      },
    };
  }

  if (model.endpoints.delete) {
    paths.delete = {
      tags: [model.name],
      summary: \`Delete \${model.name}\`,
      description: \`Delete a \${model.name}\`,
      operationId: \`delete\${model.name}\`,
      parameters: [{ $ref: '#/components/parameters/IdParameter' }],
      responses: {
        '200': {
          description: 'Deleted successfully',
          content: {
            'application/json': {
              schema: {
                type: 'object',
                properties: { message: { type: 'string' } },
              },
            },
          },
        },
        '404': { $ref: '#/components/responses/NotFound' },
        '500': { $ref: '#/components/responses/ServerError' },
      },
    };
  }

  return paths;
};

const buildOneToManyPath = (model: ModelMeta, rel: RelationshipMeta): OpenAPI.PathItemObject => ({
  get: {
    tags: [model.name],
    summary: \`Get \${rel.target} list for \${model.name}\`,
    description: \`Retrieve all \${rel.target} records associated with a \${model.name}\`,
    operationId: \`get\${model.name}\${rel.target}List\`,
    parameters: [{ $ref: '#/components/parameters/IdParameter' }],
    responses: {
      '200': {
        description: 'Successful response',
        content: {
          'application/json': {
            schema: { type: 'array', items: { type: 'object' } },
          },
        },
      },
      '404': { $ref: '#/components/responses/NotFound' },
      '500': { $ref: '#/components/responses/ServerError' },
    },
  },
});

const buildManyToManyListPaths = (model: ModelMeta, rel: RelationshipMeta): OpenAPI.PathItemObject => {
  const capitalize = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
  const relNameCap = capitalize(rel.name);
  const junctionSchema = { type: 'string' as const, format: 'uuid', description: 'ID of the related resource' };

  return {
    get: {
      tags: [model.name],
      summary: \`Get \${rel.name} for \${model.name}\`,
      description: \`Retrieve all \${rel.name} associated with a \${model.name}\`,
      operationId: \`get\${model.name}\${relNameCap}\`,
      parameters: [{ $ref: '#/components/parameters/IdParameter' }],
      responses: {
        '200': {
          description: 'Successful response',
          content: {
            'application/json': {
              schema: { type: 'array', items: { $ref: \`#/components/schemas/\${rel.target}\` } },
            },
          },
        },
        '404': { $ref: '#/components/responses/NotFound' },
        '500': { $ref: '#/components/responses/ServerError' },
      },
    },
    post: {
      tags: [model.name],
      summary: \`Add \${rel.name} to \${model.name}\`,
      description: \`Add multiple \${rel.name} to a \${model.name}\`,
      operationId: \`add\${model.name}\${relNameCap}\`,
      parameters: [{ $ref: '#/components/parameters/IdParameter' }],
      requestBody: {
        required: true,
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                [rel.name]: { type: 'array', items: junctionSchema, description: \`Array of \${rel.name} IDs\` },
              },
              required: [rel.name],
            },
          },
        },
      },
      responses: {
        '201': {
          description: 'Added successfully',
          content: { 'application/json': { schema: { type: 'object', properties: { message: { type: 'string' } } } } },
        },
        '404': { $ref: '#/components/responses/NotFound' },
        '500': { $ref: '#/components/responses/ServerError' },
      },
    },
    put: {
      tags: [model.name],
      summary: \`Replace \${rel.name} for \${model.name}\`,
      description: \`Replace all \${rel.name} for a \${model.name}\`,
      operationId: \`set\${model.name}\${relNameCap}\`,
      parameters: [{ $ref: '#/components/parameters/IdParameter' }],
      requestBody: {
        required: true,
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                [rel.name]: { type: 'array', items: junctionSchema, description: \`Array of \${rel.name} IDs\` },
              },
              required: [rel.name],
            },
          },
        },
      },
      responses: {
        '200': {
          description: 'Updated successfully',
          content: { 'application/json': { schema: { type: 'object', properties: { message: { type: 'string' } } } } },
        },
        '404': { $ref: '#/components/responses/NotFound' },
        '500': { $ref: '#/components/responses/ServerError' },
      },
    },
    delete: {
      tags: [model.name],
      summary: \`Remove \${rel.name} from \${model.name}\`,
      description: \`Remove multiple \${rel.name} from a \${model.name}\`,
      operationId: \`remove\${model.name}\${relNameCap}\`,
      parameters: [{ $ref: '#/components/parameters/IdParameter' }],
      requestBody: {
        required: true,
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: { ids: { type: 'array', items: { type: 'string', format: 'uuid' } } },
            },
          },
        },
      },
      responses: {
        '200': {
          description: 'Removed successfully',
          content: { 'application/json': { schema: { type: 'object', properties: { message: { type: 'string' } } } } },
        },
        '404': { $ref: '#/components/responses/NotFound' },
        '500': { $ref: '#/components/responses/ServerError' },
      },
    },
  };
};

const buildManyToManyDetailPaths = (model: ModelMeta, rel: RelationshipMeta): OpenAPI.PathItemObject => {
  const targetLower = rel.target.toLowerCase();

  return {
    post: {
      tags: [model.name],
      summary: \`Add a \${rel.target} to \${model.name}\`,
      description: \`Add a specific \${rel.target} to a \${model.name}\`,
      operationId: \`add\${model.name}\${rel.target}\`,
      parameters: [
        { $ref: '#/components/parameters/IdParameter' },
        { name: \`\${targetLower}Id\`, in: 'path', required: true, schema: { type: 'string', format: 'uuid' } },
      ],
      responses: {
        '201': {
          description: 'Added successfully',
          content: { 'application/json': { schema: { type: 'object', properties: { message: { type: 'string' } } } } },
        },
        '404': { $ref: '#/components/responses/NotFound' },
        '500': { $ref: '#/components/responses/ServerError' },
      },
    },
    delete: {
      tags: [model.name],
      summary: \`Remove a \${rel.target} from \${model.name}\`,
      description: \`Remove a specific \${rel.target} from a \${model.name}\`,
      operationId: \`remove\${model.name}\${rel.target}\`,
      parameters: [
        { $ref: '#/components/parameters/IdParameter' },
        { name: \`\${targetLower}Id\`, in: 'path', required: true, schema: { type: 'string', format: 'uuid' } },
      ],
      responses: {
        '200': {
          description: 'Removed successfully',
          content: { 'application/json': { schema: { type: 'object', properties: { message: { type: 'string' } } } } },
        },
        '404': { $ref: '#/components/responses/NotFound' },
        '500': { $ref: '#/components/responses/ServerError' },
      },
    },
  };
};

// ============================================
// Common Components
// ============================================

const buildCommonSchemas = (): Record<string, OpenAPI.SchemaObject> => ({
  FilterCondition: {
    type: 'object',
    description: 'A single filter condition',
    properties: {
      field: { type: 'string', description: 'Field name to filter on' },
      op: {
        type: 'string',
        enum: ['eq', 'neq', 'gt', 'gte', 'lt', 'lte', 'like', 'ilike', 'in', 'nin', 'isNull', 'contains', 'overlaps'],
        description: 'Filter operator',
      },
      value: { description: 'Value to compare against' },
    },
    required: ['field', 'op', 'value'],
  },
  FilterGroup: {
    type: 'object',
    description: 'Logical grouping of filter conditions',
    properties: {
      and: {
        type: 'array',
        items: { oneOf: [{ $ref: '#/components/schemas/FilterCondition' }, { $ref: '#/components/schemas/FilterGroup' }] },
        description: 'All conditions must match (logical AND)',
      },
      or: {
        type: 'array',
        items: { oneOf: [{ $ref: '#/components/schemas/FilterCondition' }, { $ref: '#/components/schemas/FilterGroup' }] },
        description: 'Any condition must match (logical OR)',
      },
    },
  },
  WhereFilter: {
    oneOf: [{ $ref: '#/components/schemas/FilterCondition' }, { $ref: '#/components/schemas/FilterGroup' }],
    description: 'Filter for querying records.',
  },
});

const buildCommonParameters = (): Record<string, OpenAPI.ParameterObject> => ({
  IdParameter: {
    name: 'id',
    in: 'path',
    required: true,
    description: 'Resource ID',
    schema: { type: 'string', format: 'uuid' },
  },
  LimitParameter: {
    name: 'limit',
    in: 'query',
    description: 'Maximum number of items to return',
    schema: { type: 'integer', default: 10, minimum: 1, maximum: 100 },
  },
  OffsetParameter: {
    name: 'offset',
    in: 'query',
    description: 'Number of items to skip',
    schema: { type: 'integer', default: 0, minimum: 0 },
  },
  OrderByParameter: {
    name: 'orderBy',
    in: 'query',
    description: 'Field to order by',
    schema: { type: 'string' },
  },
  OrderDirectionParameter: {
    name: 'orderDirection',
    in: 'query',
    description: 'Order direction',
    schema: { type: 'string', enum: ['asc', 'desc'], default: 'asc' },
  },
  WhereParameter: {
    name: 'where',
    in: 'query',
    description: 'Base64-encoded JSON filter for querying records.',
    schema: { type: 'string', format: 'base64' },
  },
});

const buildCommonResponses = (): Record<string, OpenAPI.ResponseObject> => ({
  NotFound: {
    description: 'Resource not found',
    content: {
      'application/json': {
        schema: { type: 'object', properties: { error: { type: 'string' } } },
      },
    },
  },
  ValidationError: {
    description: 'Validation error',
    content: {
      'application/json': {
        schema: {
          type: 'object',
          properties: {
            error: { type: 'string' },
            issues: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  path: { type: 'array', items: { type: 'string' } },
                  message: { type: 'string' },
                },
              },
            },
          },
        },
      },
    },
  },
  ServerError: {
    description: 'Internal server error',
    content: {
      'application/json': {
        schema: {
          type: 'object',
          properties: { error: { type: 'string' }, requestId: { type: 'string' } },
        },
      },
    },
  },
});
`;
  }
}
